/* This file was automatically generated. */
pub mod traits;
pub mod defs;

#[cfg(feature = "ActionButtonParam")]
pub mod ActionButtonParam;
#[cfg(feature = "AiSoundParam")]
pub mod AiSoundParam;
#[cfg(feature = "AssetEnvironmentGeometryParam")]
pub mod AssetEnvironmentGeometryParam;
#[cfg(feature = "AssetMaterialSfxParam")]
pub mod AssetMaterialSfxParam;
#[cfg(feature = "AssetModelSfxParam")]
pub mod AssetModelSfxParam;
#[cfg(feature = "AtkParam_Npc")]
pub mod AtkParam_Npc;
#[cfg(feature = "AtkParam_Pc")]
pub mod AtkParam_Pc;
#[cfg(feature = "AttackElementCorrectParam")]
pub mod AttackElementCorrectParam;
#[cfg(feature = "AutoCreateEnvSoundParam")]
pub mod AutoCreateEnvSoundParam;
#[cfg(feature = "BaseChrSelectMenuParam")]
pub mod BaseChrSelectMenuParam;
#[cfg(feature = "BehaviorParam")]
pub mod BehaviorParam;
#[cfg(feature = "BehaviorParam_PC")]
pub mod BehaviorParam_PC;
#[cfg(feature = "BonfireWarpParam")]
pub mod BonfireWarpParam;
#[cfg(feature = "BonfireWarpSubCategoryParam")]
pub mod BonfireWarpSubCategoryParam;
#[cfg(feature = "BonfireWarpTabParam")]
pub mod BonfireWarpTabParam;
#[cfg(feature = "BuddyParam")]
pub mod BuddyParam;
#[cfg(feature = "BuddyStoneParam")]
pub mod BuddyStoneParam;
#[cfg(feature = "BudgetParam")]
pub mod BudgetParam;
#[cfg(feature = "Bullet")]
pub mod Bullet;
#[cfg(feature = "BulletCreateLimitParam")]
pub mod BulletCreateLimitParam;
#[cfg(feature = "CalcCorrectGraph")]
pub mod CalcCorrectGraph;
#[cfg(feature = "Ceremony")]
pub mod Ceremony;
#[cfg(feature = "CharaInitParam")]
pub mod CharaInitParam;
#[cfg(feature = "CharMakeMenuListItemParam")]
pub mod CharMakeMenuListItemParam;
#[cfg(feature = "CharMakeMenuTopParam")]
pub mod CharMakeMenuTopParam;
#[cfg(feature = "ChrActivateConditionParam")]
pub mod ChrActivateConditionParam;
#[cfg(feature = "ChrModelParam")]
pub mod ChrModelParam;
#[cfg(feature = "ClearCountCorrectParam")]
pub mod ClearCountCorrectParam;
#[cfg(feature = "CoolTimeParam")]
pub mod CoolTimeParam;
#[cfg(feature = "CutsceneGparamTimeParam")]
pub mod CutsceneGparamTimeParam;
#[cfg(feature = "CutsceneGparamWeatherParam")]
pub mod CutsceneGparamWeatherParam;
#[cfg(feature = "CutsceneMapIdParam")]
pub mod CutsceneMapIdParam;
#[cfg(feature = "CutSceneTextureLoadParam")]
pub mod CutSceneTextureLoadParam;
#[cfg(feature = "CutsceneTimezoneConvertParam")]
pub mod CutsceneTimezoneConvertParam;
#[cfg(feature = "CutsceneWeatherOverrideGparamConvertParam")]
pub mod CutsceneWeatherOverrideGparamConvertParam;
#[cfg(feature = "DecalParam")]
pub mod DecalParam;
#[cfg(feature = "DirectionCameraParam")]
pub mod DirectionCameraParam;
#[cfg(feature = "EnemyCommonParam")]
pub mod EnemyCommonParam;
#[cfg(feature = "EnvObjLotParam")]
pub mod EnvObjLotParam;
#[cfg(feature = "EquipMtrlSetParam")]
pub mod EquipMtrlSetParam;
#[cfg(feature = "EquipParamAccessory")]
pub mod EquipParamAccessory;
#[cfg(feature = "EquipParamCustomWeapon")]
pub mod EquipParamCustomWeapon;
#[cfg(feature = "EquipParamGem")]
pub mod EquipParamGem;
#[cfg(feature = "EquipParamGoods")]
pub mod EquipParamGoods;
#[cfg(feature = "EquipParamProtector")]
pub mod EquipParamProtector;
#[cfg(feature = "EquipParamWeapon")]
pub mod EquipParamWeapon;
#[cfg(feature = "FaceParam")]
pub mod FaceParam;
#[cfg(feature = "FaceRangeParam")]
pub mod FaceRangeParam;
#[cfg(feature = "FeTextEffectParam")]
pub mod FeTextEffectParam;
#[cfg(feature = "FinalDamageRateParam")]
pub mod FinalDamageRateParam;
#[cfg(feature = "FootSfxParam")]
pub mod FootSfxParam;
#[cfg(feature = "GameAreaParam")]
pub mod GameAreaParam;
#[cfg(feature = "GameSystemCommonParam")]
pub mod GameSystemCommonParam;
#[cfg(feature = "GestureParam")]
pub mod GestureParam;
#[cfg(feature = "GparamRefSettings")]
pub mod GparamRefSettings;
#[cfg(feature = "GraphicsCommonParam")]
pub mod GraphicsCommonParam;
#[cfg(feature = "GraphicsConfig")]
pub mod GraphicsConfig;
#[cfg(feature = "GrassLodRangeParam")]
pub mod GrassLodRangeParam;
#[cfg(feature = "GrassTypeParam")]
pub mod GrassTypeParam;
#[cfg(feature = "GrassTypeParam_Lv1")]
pub mod GrassTypeParam_Lv1;
#[cfg(feature = "GrassTypeParam_Lv2")]
pub mod GrassTypeParam_Lv2;
#[cfg(feature = "HitEffectSeParam")]
pub mod HitEffectSeParam;
#[cfg(feature = "HitEffectSfxConceptParam")]
pub mod HitEffectSfxConceptParam;
#[cfg(feature = "HitEffectSfxParam")]
pub mod HitEffectSfxParam;
#[cfg(feature = "HitMtrlParam")]
pub mod HitMtrlParam;
#[cfg(feature = "HPEstusFlaskRecoveryParam")]
pub mod HPEstusFlaskRecoveryParam;
#[cfg(feature = "ItemLotParam_enemy")]
pub mod ItemLotParam_enemy;
#[cfg(feature = "ItemLotParam_map")]
pub mod ItemLotParam_map;
#[cfg(feature = "KeyAssignMenuItemParam")]
pub mod KeyAssignMenuItemParam;
#[cfg(feature = "KeyAssignParam_TypeA")]
pub mod KeyAssignParam_TypeA;
#[cfg(feature = "KeyAssignParam_TypeB")]
pub mod KeyAssignParam_TypeB;
#[cfg(feature = "KeyAssignParam_TypeC")]
pub mod KeyAssignParam_TypeC;
#[cfg(feature = "KnockBackParam")]
pub mod KnockBackParam;
#[cfg(feature = "KnowledgeLoadScreenItemParam")]
pub mod KnowledgeLoadScreenItemParam;
#[cfg(feature = "LegacyDistantViewPartsReplaceParam")]
pub mod LegacyDistantViewPartsReplaceParam;
#[cfg(feature = "LoadBalancerDrawDistScaleParam")]
pub mod LoadBalancerDrawDistScaleParam;
#[cfg(feature = "LoadBalancerDrawDistScaleParam_ps4")]
pub mod LoadBalancerDrawDistScaleParam_ps4;
#[cfg(feature = "LoadBalancerDrawDistScaleParam_ps5")]
pub mod LoadBalancerDrawDistScaleParam_ps5;
#[cfg(feature = "LoadBalancerDrawDistScaleParam_xb1")]
pub mod LoadBalancerDrawDistScaleParam_xb1;
#[cfg(feature = "LoadBalancerDrawDistScaleParam_xb1x")]
pub mod LoadBalancerDrawDistScaleParam_xb1x;
#[cfg(feature = "LoadBalancerDrawDistScaleParam_xss")]
pub mod LoadBalancerDrawDistScaleParam_xss;
#[cfg(feature = "LoadBalancerDrawDistScaleParam_xsx")]
pub mod LoadBalancerDrawDistScaleParam_xsx;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_ps4")]
pub mod LoadBalancerNewDrawDistScaleParam_ps4;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_ps5")]
pub mod LoadBalancerNewDrawDistScaleParam_ps5;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_win64")]
pub mod LoadBalancerNewDrawDistScaleParam_win64;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_xb1")]
pub mod LoadBalancerNewDrawDistScaleParam_xb1;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_xb1x")]
pub mod LoadBalancerNewDrawDistScaleParam_xb1x;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_xss")]
pub mod LoadBalancerNewDrawDistScaleParam_xss;
#[cfg(feature = "LoadBalancerNewDrawDistScaleParam_xsx")]
pub mod LoadBalancerNewDrawDistScaleParam_xsx;
#[cfg(feature = "LoadBalancerParam")]
pub mod LoadBalancerParam;
#[cfg(feature = "LockCamParam")]
pub mod LockCamParam;
#[cfg(feature = "Magic")]
pub mod Magic;
#[cfg(feature = "MapDefaultInfoParam")]
pub mod MapDefaultInfoParam;
#[cfg(feature = "MapGdRegionDrawParam")]
pub mod MapGdRegionDrawParam;
#[cfg(feature = "MapGdRegionInfoParam")]
pub mod MapGdRegionInfoParam;
#[cfg(feature = "MapGridCreateHeightLimitInfoParam")]
pub mod MapGridCreateHeightLimitInfoParam;
#[cfg(feature = "MapMimicryEstablishmentParam")]
pub mod MapMimicryEstablishmentParam;
#[cfg(feature = "MapNameTexParam")]
pub mod MapNameTexParam;
#[cfg(feature = "MapPieceTexParam")]
pub mod MapPieceTexParam;
#[cfg(feature = "MaterialExParam")]
pub mod MaterialExParam;
#[cfg(feature = "MenuColorTableParam")]
pub mod MenuColorTableParam;
#[cfg(feature = "MenuCommonParam")]
pub mod MenuCommonParam;
#[cfg(feature = "MenuOffscrRendParam")]
pub mod MenuOffscrRendParam;
#[cfg(feature = "MenuPropertyLayoutParam")]
pub mod MenuPropertyLayoutParam;
#[cfg(feature = "MenuPropertySpecParam")]
pub mod MenuPropertySpecParam;
#[cfg(feature = "MenuValueTableParam")]
pub mod MenuValueTableParam;
#[cfg(feature = "MimicryEstablishmentTexParam")]
pub mod MimicryEstablishmentTexParam;
#[cfg(feature = "MoveParam")]
pub mod MoveParam;
#[cfg(feature = "MPEstusFlaskRecoveryParam")]
pub mod MPEstusFlaskRecoveryParam;
#[cfg(feature = "MultiHPEstusFlaskBonusParam")]
pub mod MultiHPEstusFlaskBonusParam;
#[cfg(feature = "MultiMPEstusFlaskBonusParam")]
pub mod MultiMPEstusFlaskBonusParam;
#[cfg(feature = "MultiPlayCorrectionParam")]
pub mod MultiPlayCorrectionParam;
#[cfg(feature = "MultiSoulBonusRateParam")]
pub mod MultiSoulBonusRateParam;
#[cfg(feature = "NetworkAreaParam")]
pub mod NetworkAreaParam;
#[cfg(feature = "NetworkMsgParam")]
pub mod NetworkMsgParam;
#[cfg(feature = "NetworkParam")]
pub mod NetworkParam;
#[cfg(feature = "NpcAiActionParam")]
pub mod NpcAiActionParam;
#[cfg(feature = "NpcAiBehaviorProbability")]
pub mod NpcAiBehaviorProbability;
#[cfg(feature = "NpcParam")]
pub mod NpcParam;
#[cfg(feature = "NpcThinkParam")]
pub mod NpcThinkParam;
#[cfg(feature = "ObjActParam")]
pub mod ObjActParam;
#[cfg(feature = "PartsDrawParam")]
pub mod PartsDrawParam;
#[cfg(feature = "PhantomParam")]
pub mod PhantomParam;
#[cfg(feature = "PlayerCommonParam")]
pub mod PlayerCommonParam;
#[cfg(feature = "PlayRegionParam")]
pub mod PlayRegionParam;
#[cfg(feature = "PostureControlParam_Gender")]
pub mod PostureControlParam_Gender;
#[cfg(feature = "PostureControlParam_Pro")]
pub mod PostureControlParam_Pro;
#[cfg(feature = "PostureControlParam_WepLeft")]
pub mod PostureControlParam_WepLeft;
#[cfg(feature = "PostureControlParam_WepRight")]
pub mod PostureControlParam_WepRight;
#[cfg(feature = "RandomAppearParam")]
pub mod RandomAppearParam;
#[cfg(feature = "ReinforceParamProtector")]
pub mod ReinforceParamProtector;
#[cfg(feature = "ReinforceParamWeapon")]
pub mod ReinforceParamWeapon;
#[cfg(feature = "ResistCorrectParam")]
pub mod ResistCorrectParam;
#[cfg(feature = "RideParam")]
pub mod RideParam;
#[cfg(feature = "RoleParam")]
pub mod RoleParam;
#[cfg(feature = "RollingObjLotParam")]
pub mod RollingObjLotParam;
#[cfg(feature = "RuntimeBoneControlParam")]
pub mod RuntimeBoneControlParam;
#[cfg(feature = "SeActivationRangeParam")]
pub mod SeActivationRangeParam;
#[cfg(feature = "SeMaterialConvertParam")]
pub mod SeMaterialConvertParam;
#[cfg(feature = "SfxBlockResShareParam")]
pub mod SfxBlockResShareParam;
#[cfg(feature = "ShopLineupParam")]
pub mod ShopLineupParam;
#[cfg(feature = "ShopLineupParam_Recipe")]
pub mod ShopLineupParam_Recipe;
#[cfg(feature = "SignPuddleParam")]
pub mod SignPuddleParam;
#[cfg(feature = "SoundAssetSoundObjEnableDistParam")]
pub mod SoundAssetSoundObjEnableDistParam;
#[cfg(feature = "SoundAutoEnvSoundGroupParam")]
pub mod SoundAutoEnvSoundGroupParam;
#[cfg(feature = "SoundAutoReverbEvaluationDistParam")]
pub mod SoundAutoReverbEvaluationDistParam;
#[cfg(feature = "SoundAutoReverbSelectParam")]
pub mod SoundAutoReverbSelectParam;
#[cfg(feature = "SoundChrPhysicsSeParam")]
pub mod SoundChrPhysicsSeParam;
#[cfg(feature = "SoundCommonIngameParam")]
pub mod SoundCommonIngameParam;
#[cfg(feature = "SoundCutsceneParam")]
pub mod SoundCutsceneParam;
#[cfg(feature = "SpeedtreeParam")]
pub mod SpeedtreeParam;
#[cfg(feature = "SpEffectParam")]
pub mod SpEffectParam;
#[cfg(feature = "SpEffectSetParam")]
pub mod SpEffectSetParam;
#[cfg(feature = "SpEffectVfxParam")]
pub mod SpEffectVfxParam;
#[cfg(feature = "SwordArtsParam")]
pub mod SwordArtsParam;
#[cfg(feature = "TalkParam")]
pub mod TalkParam;
#[cfg(feature = "ThrowDirectionSfxParam")]
pub mod ThrowDirectionSfxParam;
#[cfg(feature = "ThrowParam")]
pub mod ThrowParam;
#[cfg(feature = "ToughnessParam")]
pub mod ToughnessParam;
#[cfg(feature = "TutorialParam")]
pub mod TutorialParam;
#[cfg(feature = "WaypointParam")]
pub mod WaypointParam;
#[cfg(feature = "WeatherAssetCreateParam")]
pub mod WeatherAssetCreateParam;
#[cfg(feature = "WeatherAssetReplaceParam")]
pub mod WeatherAssetReplaceParam;
#[cfg(feature = "WeatherLotParam")]
pub mod WeatherLotParam;
#[cfg(feature = "WeatherLotTexParam")]
pub mod WeatherLotTexParam;
#[cfg(feature = "WeatherParam")]
pub mod WeatherParam;
#[cfg(feature = "WepAbsorpPosParam")]
pub mod WepAbsorpPosParam;
#[cfg(feature = "WetAspectParam")]
pub mod WetAspectParam;
#[cfg(feature = "WhiteSignCoolTimeParam")]
pub mod WhiteSignCoolTimeParam;
#[cfg(feature = "WorldMapLegacyConvParam")]
pub mod WorldMapLegacyConvParam;
#[cfg(feature = "WorldMapPieceParam")]
pub mod WorldMapPieceParam;
#[cfg(feature = "WorldMapPlaceNameParam")]
pub mod WorldMapPlaceNameParam;
#[cfg(feature = "WorldMapPointParam")]
pub mod WorldMapPointParam;
#[cfg(feature = "WwiseValueToStrParam_BgmBossChrIdConv")]
pub mod WwiseValueToStrParam_BgmBossChrIdConv;
#[cfg(feature = "WwiseValueToStrParam_EnvPlaceType")]
pub mod WwiseValueToStrParam_EnvPlaceType;
#[cfg(feature = "WwiseValueToStrParam_Switch_AttackStrength")]
pub mod WwiseValueToStrParam_Switch_AttackStrength;
#[cfg(feature = "WwiseValueToStrParam_Switch_AttackType")]
pub mod WwiseValueToStrParam_Switch_AttackType;
#[cfg(feature = "WwiseValueToStrParam_Switch_DamageAmount")]
pub mod WwiseValueToStrParam_Switch_DamageAmount;
#[cfg(feature = "WwiseValueToStrParam_Switch_DeffensiveMaterial")]
pub mod WwiseValueToStrParam_Switch_DeffensiveMaterial;
#[cfg(feature = "WwiseValueToStrParam_Switch_GrassHitType")]
pub mod WwiseValueToStrParam_Switch_GrassHitType;
#[cfg(feature = "WwiseValueToStrParam_Switch_HitStop")]
pub mod WwiseValueToStrParam_Switch_HitStop;
#[cfg(feature = "WwiseValueToStrParam_Switch_OffensiveMaterial")]
pub mod WwiseValueToStrParam_Switch_OffensiveMaterial;
#[cfg(feature = "WwiseValueToStrParam_Switch_PlayerEquipmentBottoms")]
pub mod WwiseValueToStrParam_Switch_PlayerEquipmentBottoms;
#[cfg(feature = "WwiseValueToStrParam_Switch_PlayerEquipmentTops")]
pub mod WwiseValueToStrParam_Switch_PlayerEquipmentTops;
#[cfg(feature = "WwiseValueToStrParam_Switch_PlayerShoes")]
pub mod WwiseValueToStrParam_Switch_PlayerShoes;
#[cfg(feature = "WwiseValueToStrParam_Switch_PlayerVoiceType")]
pub mod WwiseValueToStrParam_Switch_PlayerVoiceType;

